### ISSUE TITLE
区别在哪？

### ISSUE THREAD

**Issue by hedeqiang** [hyperf-libraries/sms#1]
没看出来和 原来的有什么区别呀？ 无非是生成下配置文件？ guzzle 也没替换呀

**Comment by qingpizi** [comment]
没有区别，后面替换，后面会有写区别




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hedeqiang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月11日(星期三) 下午5:59
收件人:&nbsp;"hyperf-libraries/sms"<sms@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[hyperf-libraries/sms] 区别在哪？ (#1)




没看出来和 原来的有什么区别呀？ 无非是生成下配置文件？ guzzle 也没替换呀
