### ISSUE TITLE
使用阿里云网关发送短信出错

### ISSUE THREAD

**Issue by cxjhk** [hyperf-libraries/sms#2]
All the gateways have failed. You can get error details by `$exception->getExceptions()`[75] in
![image](https://user-images.githubusercontent.com/23472375/71050862-5fcd2880-2181-11ea-8945-5c012d8e4787.png)
![image](https://user-images.githubusercontent.com/23472375/71050893-73788f00-2181-11ea-9c9f-d691d4adc6eb.png)

**Comment by qingpizi** [comment]
aliyun短信服务修复了下
可以这样拿到比较详细的报错
try{
            $client = $this->getClient();
            $result = $client->send('', [ //手机号码
                                          'content'  => '', //短信内容
                                          'template' => '', //模板id
                                          'data' => [
                                              'code' => //验证码
                                          ]
            ]);
            var_dump($result);
        }catch (NoGatewayAvailableException $exception) {
            echo 'Error:' . $exception->getException('aliyun')->getMessage().' '.$exception->getException('aliyun')->getFile().' '.$exception->getException('aliyun')->getLine();
        }
