### ISSUE TITLE
支持下hyperf2.0

### ISSUE THREAD

**Issue by guanhui07** [hyperf-libraries/sms#3]
支持下hyperf2.0 ,hyperf2.0发布了 包的composer依赖 支持下

**Comment by lionXu86** [comment]
同上，把hyperf/guzzle依赖生成2.0及以上吧

**Comment by qingpizi** [comment]
> 同上，把hyperf/guzzle依赖生成2.0及以上吧

支持了

**Comment by qingpizi** [comment]
> 支持下hyperf2.0 ,hyperf2.0发布了 包的composer依赖 支持下

支持了
